name: diet_delight
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_text_field: ^1.7.1
  flutter_rounded_date_picker: ^1.0.5+1
  email_validator: ^1.0.6
  oauth2: ^1.6.3
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  flutter_open_whatsapp: ^0.1.2
  flutter_dropdown: ^0.0.8
  date_format: ^1.0.9
  cached_network_image: ^2.5.0
  url_launcher: ^5.7.10
  flutter_downloader: ^1.5.2
  path_provider: ^1.6.9
  permission_handler: ^4.0.0
#  flutter_svg: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: RobotoReg
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: RobotoCondensedReg
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
    - family: ABeeZeeReg
      fonts:
        - asset: fonts/ABeeZee-Regular.ttf
    - family: MontserratMed
      fonts:
        - asset: fonts/Montserrat-Medium.ttf